networks:
  default:
    driver: bridge

services:

  nginx:
    image: nginx:1.23.4
    tty: true
    restart: 'no'
    ports:
      - ${NGINX_PORT:-8080}:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - auth-app
      - service-app

  auth-app:
    build:
      context: .
      dockerfile: docker-app/Dockerfile
      args:
        - UID=1000
        - GID=1000
    tty: true
    restart: 'no'
    ports:
      - 8081:8080
    volumes:
      - ./docker-app/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./docker-app/ports.conf:/etc/apache2/ports.conf
      - ./auth-app:/home/app/html

  service-app:
    build:
      context: .
      dockerfile: docker-app/Dockerfile
      args:
        - UID=1000
        - GID=1000
    tty: true
    restart: 'no'
    ports:
      - 8082:8080
    volumes:
      - ./docker-app/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./docker-app/ports.conf:/etc/apache2/ports.conf
      - ./service-app:/home/app/html
